server:   
      port: 8888  
eureka:  
       instance:   
           hostname: 127.0.0.1 
           # ${server.port}为该服务的端口号   
           status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html 
       client:   
            registerWithEureka: false  
            fetchRegistry: false  
            serviceUrl:   
                     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/