# 启动端口号 http://localhost:8090/
server:
 port: 8090
 
# datasource 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
 
#security  http://localhost:8090/manage/env
management.contextPath: /manage
security.user.name: admin 
security.user.password: 123456 
management.security.enabled: true 
management.security.role: ADMIN
 
#health http://localhost:54001/manage/health
management:  
 port: 54001  
 health:  
 mail:  
 enabled: true  
#info   http://localhost:54001/manage/info   
info:  
  app:  
  name: "@project.name@" #从pom.xml中获取  
  description: "@project.description@"  
  version: "@project.version@"  
  spring-boot-version: "@project.parent.version@"
    
 
# 输出日志