server:
  port: 8040
# http://localhost:8040/neo-config/dev
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/markin01/springcloud-config.git    # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          label: master
          username: 314513963@qq.com                                             # git仓库的账号
          password: mn19870719                                            # git仓库的密码